services:
  postgres:
    image: postgres:16
    container_name: teknotes_db
    env_file:
      - .env
    ports:
      - "8002:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
