# Generated by Django 5.1.1 on 2024-10-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('red-500', 'Red'), ('orange-500', 'Orange'), ('amber-500', 'Amber'), ('lime-500', 'Lime'), ('green-500', 'Green'), ('emerald-500', 'Emerald'), ('teal-500', 'Teal'), ('cyan-500', 'Cyan'), ('blue-500', 'Blue'), ('indigo-500', 'Indigo'), ('violet-500', 'Violet'), ('purple-500', 'Purple'), ('fuschia-500', 'Fuschia'), ('pink-500', 'Pink')], default='gray-500', max_length=20)),
            ],
        ),
    ]
