# Generated by Django 5.1.1 on 2024-10-06 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='likes',
        ),
    ]
