# Generated by Django 5.1.2 on 2024-11-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
