# Generated by Django 5.1.2 on 2024-11-03 13:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Lorem ipsum', verbose_name='Text'),
        ),
    ]
