# Generated by Django 5.1.2 on 2024-11-03 13:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='I love this note!', verbose_name='Text'),
        ),
    ]
