# Generated by Django 5.1.1 on 2024-10-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_draft',
            new_name='is_archived',
        ),
    ]
