# Generated by Django 5.1.1 on 2024-10-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_is_draft_note_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
