# Generated by Django 5.1.1 on 2024-10-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_public',
            new_name='is_private',
        ),
    ]
